import type { CSSProperties } from "react";

export const s = {
  body: { padding: "20px 24px 32px", overflow: "auto" } satisfies CSSProperties,
  dropZone: (dragging: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "16px 14px",
    borderRadius: 8,
    border: "1px dashed " + (dragging ? "var(--accent)" : "var(--border-strong)"),
    background: dragging ? "var(--accent-bg)" : "var(--bg-elevated)",
    transition: "background .12s ease, border-color .12s ease",
  }),
  hiddenInput: { display: "none" } satisfies CSSProperties,
  dropHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  error: {
    fontSize: 12,
    color: "var(--crit)",
    background: "var(--crit-bg)",
    padding: "8px 10px",
    borderRadius: 6,
    marginBottom: 16,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  skipped: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "12px 14px",
    marginBottom: 20,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  skippedHead: { marginBottom: 8 } satisfies CSSProperties,
  skippedList: {
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 3,
    maxHeight: 132,
    overflow: "auto",
  } satisfies CSSProperties,
  skippedItem: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  trust: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    padding: "10px 12px",
    borderRadius: 6,
    marginBottom: 16,
  } satisfies CSSProperties,
  previewCard: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "16px 18px",
    background: "var(--bg-elevated)",
    maxHeight: 340,
    overflow: "auto",
  } satisfies CSSProperties,
  footer: { display: "flex", justifyContent: "flex-end", gap: 10 } satisfies CSSProperties,
} as const;
