import type { CSSProperties } from "react";

/** Co-located styles for AddSkillDrawer. */
export const s = {
  tabsBar: { marginBottom: 18 } satisfies CSSProperties,
  pickRow: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  pickedName: {
    fontSize: 13,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  hiddenInput: { display: "none" } satisfies CSSProperties,
  error: {
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    fontSize: 12,
    color: "var(--text-primary)",
    marginTop: 14,
  } satisfies CSSProperties,
  previewWrap: { marginTop: 20 } satisfies CSSProperties,
  previewHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 4,
  } satisfies CSSProperties,
  previewTitle: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  previewHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    margin: "10px 0 12px",
  } satisfies CSSProperties,
  warning: {
    display: "flex",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    marginBottom: 14,
  } satisfies CSSProperties,
  warningIcon: { color: "var(--warn)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  ignoredList: {
    margin: "0 0 14px",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px dashed var(--border-strong)",
    fontSize: 12,
    color: "var(--text-muted)",
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  ignoredHint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 8 } satisfies CSSProperties,
  bodyBox: {
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-base)",
    maxHeight: 320,
    overflow: "auto",
    fontSize: 13,
  } satisfies CSSProperties,
  unavailable: {
    padding: "14px 16px",
    borderRadius: 8,
    border: "1px dashed var(--border-strong)",
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
} as const;
