import type { CSSProperties } from "react";

/** Co-located styles for the Blast Radius viewer (extracted from inline styles). */
export const s = {
  root: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  emptySummary: { fontSize: 14, color: "var(--text-secondary)" } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "center", gap: 14 } satisfies CSSProperties,
  summary: { display: "flex", gap: 18, flexWrap: "wrap", alignItems: "center" } satisfies CSSProperties,
  stat: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "var(--text-secondary)",
    fontSize: 13,
  } satisfies CSSProperties,
  statIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  statValue: { color: "var(--text-primary)", fontWeight: 650 } satisfies CSSProperties,
  viewToggle: {
    marginLeft: "auto",
    display: "flex",
    gap: 5,
    background: "var(--bg-hover)",
    borderRadius: 6,
    padding: 2,
  } satisfies CSSProperties,
  toggleBtn: (active: boolean): CSSProperties => ({
    border: "none",
    background: active ? "var(--bg-elevated)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-muted)",
    fontSize: 12,
    fontWeight: 600,
    padding: "4px 12px",
    borderRadius: 5,
    cursor: "pointer",
    textTransform: "capitalize",
  }),
  summaryText: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  tree: { display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  treeEmpty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  // Controls row above the tree: hint on the left, expand/collapse-all on the right.
  treeControls: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "0 4px 8px",
    borderBottom: "1px solid var(--border)",
    marginBottom: 4,
  } satisfies CSSProperties,
  hintIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  textBtn: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 600,
    padding: "3px 9px",
    borderRadius: 5,
    cursor: "pointer",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  // DownstreamNode
  node: { borderRadius: 6 } satisfies CSSProperties,
  nodeHeader: (open: boolean, alert: "crit" | "warn" | null): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "6px 8px",
    borderRadius: 6,
    cursor: "pointer",
    flexWrap: "wrap",
    background: open ? "var(--bg-hover)" : "transparent",
    // Left accent when the changed symbol carries a critical/warning signal.
    boxShadow: alert
      ? `inset 3px 0 0 ${alert === "crit" ? "var(--crit)" : "var(--warn)"}`
      : undefined,
  }),
  // Risk / breaking chip.
  chip: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11,
    fontWeight: 600,
    color,
    background: "color-mix(in srgb, currentColor 12%, transparent)",
    border: "1px solid color-mix(in srgb, currentColor 30%, transparent)",
    borderRadius: 4,
    padding: "1px 6px",
    whiteSpace: "nowrap",
  }),
  // Caller role pill (business/test/boilerplate).
  roleTag: (color: string): CSSProperties => ({
    fontSize: 10.5,
    fontWeight: 600,
    color,
    background: "color-mix(in srgb, currentColor 12%, transparent)",
    borderRadius: 4,
    padding: "0 5px",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  }),
  // Existing-finding cross-reference badge on a symbol row.
  findingBadge: (color: string, bg: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11,
    fontWeight: 600,
    color,
    background: bg,
    borderRadius: 4,
    padding: "1px 6px",
    whiteSpace: "nowrap",
  }),
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(90deg)" : "none",
    transition: "transform .12s",
  }),
  nodeIcon: { color: "var(--accent)" } satisfies CSSProperties,
  nodeSymbol: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  nodeCallerCount: { fontSize: 12, color: "var(--text-muted)", marginLeft: "auto" } satisfies CSSProperties,
  callerList: {
    padding: "5px 0 10px 24px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  callerRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13 } satisfies CSSProperties,
  callerIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  callerName: { color: "var(--text-secondary)" } satisfies CSSProperties,
  // Caller location + a subtle "open in Files" affordance (revealed via CSS hover).
  callerLink: { display: "inline-flex", alignItems: "center", gap: 4 } satisfies CSSProperties,
  openHint: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  badgeWrap: { display: "inline-flex" } satisfies CSSProperties,
  badgeRow: { display: "flex", gap: 8, flexWrap: "wrap", padding: "8px 0 0 24px" } satisfies CSSProperties,
  cronBadgeRow: { display: "flex", gap: 8, flexWrap: "wrap", padding: "5px 0 0 24px" } satisfies CSSProperties,
  // BlastGraph
  graphWrap: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  graphEmpty: { fontSize: 13, color: "var(--text-muted)", padding: 14 } satisfies CSSProperties,
  graphSvg: { maxWidth: "100%" } satisfies CSSProperties,
  legend: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap",
    fontSize: 11.5,
    color: "var(--text-muted)",
    padding: "2px 4px",
  } satisfies CSSProperties,
  legendItem: { display: "inline-flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  legendSwatch: {
    width: 11,
    height: 11,
    borderRadius: 3,
    border: "1.5px solid",
    background: "var(--bg-elevated)",
    display: "inline-block",
  } satisfies CSSProperties,
  // "No agent has reviewed yet" note.
  notReviewed: {
    fontSize: 12,
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  // Dead / uncalled changed symbols.
  deadSection: { marginTop: 10, paddingTop: 10, borderTop: "1px solid var(--border)" } satisfies CSSProperties,
  deadTitle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  deadRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13, padding: "3px 8px" } satisfies CSSProperties,
  deadIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  deadName: { color: "var(--text-muted)", textDecoration: "line-through" } satisfies CSSProperties,
  deadTag: {
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    borderRadius: 4,
    padding: "0 6px",
  } satisfies CSSProperties,
  // Related PRs (collapsible).
  relatedSection: { marginTop: 10, paddingTop: 10, borderTop: "1px solid var(--border)" } satisfies CSSProperties,
  relatedHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    padding: "4px 8px",
    borderRadius: 6,
  } satisfies CSSProperties,
  relatedIcon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  relatedTitle: { fontSize: 13, fontWeight: 600, color: "var(--text-secondary)" } satisfies CSSProperties,
  relatedCount: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    borderRadius: 10,
    padding: "0 7px",
  } satisfies CSSProperties,
  relatedList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: "6px 0 0 26px",
  } satisfies CSSProperties,
  relatedRow: { display: "flex", alignItems: "center", gap: 8, fontSize: 13 } satisfies CSSProperties,
  relatedNum: { fontSize: 12, fontWeight: 700, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  relatedPrTitle: { color: "var(--text-secondary)" } satisfies CSSProperties,
} as const;
